#!/usr/bin/env bash
#create a file and display to infinity

echo $BASHPID > /var/run/holbertonscript.pid

trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0;' SIGTERM
trap 'echo "Y U no love me?!"; exit 0;' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
